name: calculator_app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0
  sqflite: any
  path_provider: any
  path: any
  intl: ^0.20.2

  cupertino_icons: ^1.0.8
  math_expressions: ^2.6.0
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  adaptive_icon_background: "#ffffff"

flutter:
  uses-material-design: true
